### PR TITLE
Add conda-forge version badge

### LINKED ISSUE #52: Add conda badge

### PR DESCRIPTION
**Pull request by zmoon**
Resolves #52

### CODE REVIEW

**Comment by jbusecke** [comment]
Do you think we should remove the pypi badge altogether?

**Comment by zmoon** [comment]
Hmm, I don't mind it, it provides a confirmation that they are in sync. But removing the PyPI badge could help position conda-forge as the preferred install method, which could be good.

**Comment by zmoon** [comment]
> how about we put pypi behind conda?

Yeah that seems like good idea. And I can also add the RTD badge, maybe after the CI status one.

**Comment by jbusecke** [comment]
> Yeah that seems like a good idea. And I can also add the RTD badge, maybe after the CI status one.

Absolutely! I am all for more badges!

**Comment by zmoon** [comment]
@jbusecke I added those new changes, should be ready to go if you are pleased with how it looks [here](https://github.com/zmoon/xmovie/blob/badge/README.md)

**Comment by jbusecke** [comment]
Dope! Thanks a lot.

**Comment by jbusecke** [comment]
Oh you should most definitely add a line to the `docs/whats-new.rst` too.

**Comment by zmoon** [comment]
> Oh you should most definitely add a line to the `docs/whats-new.rst` too.

Done!

**Review by jbusecke — APPROVED** [review]
Horray! Always good to close the old year out with more badges!

**Pull request merged**
